#!/bin/bash
# Wire a project repo up to claude-global-config.
#
# Writes .claude/hooks/session-start.sh and registers it as a SessionStart
# hook in .claude/settings.json. Run it once per project:
#
#   bash /path/to/claude-global-config/add-hook.sh [project-dir]
#
# Defaults to the current directory. Idempotent — re-running refreshes the
# hook script and leaves an already-registered hook alone.
set -euo pipefail

PROJECT_DIR="$(cd "${1:-$PWD}" && pwd)"
HOOK_PATH=".claude/hooks/session-start.sh"
HOOK_FILE="$PROJECT_DIR/$HOOK_PATH"
SETTINGS_FILE="$PROJECT_DIR/.claude/settings.json"
HOOK_COMMAND='$CLAUDE_PROJECT_DIR/.claude/hooks/session-start.sh'

if [ ! -d "$PROJECT_DIR/.git" ]; then
  echo "error: $PROJECT_DIR is not a git repository" >&2
  exit 1
fi

mkdir -p "$PROJECT_DIR/.claude/hooks"

cat > "$HOOK_FILE" <<'HOOK'
#!/bin/bash
# Sync konbinipolska-alt/claude-global-config into ~/.claude/ before the
# session starts. Generated by that repo's add-hook.sh — edit it there.
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

REPO_URL="https://github.com/konbinipolska-alt/claude-global-config.git"
SYNC_DIR="$HOME/.claude-global-config-sync"

if [ -d "$SYNC_DIR/.git" ]; then
  git -C "$SYNC_DIR" pull --ff-only origin main
else
  rm -rf "$SYNC_DIR"
  git clone --depth 1 "$REPO_URL" "$SYNC_DIR"
fi

bash "$SYNC_DIR/install.sh"
HOOK

chmod +x "$HOOK_FILE"
echo "wrote $HOOK_PATH"

register_hook() {
  if command -v python3 >/dev/null 2>&1; then
    SETTINGS_FILE="$SETTINGS_FILE" HOOK_COMMAND="$HOOK_COMMAND" python3 - <<'PY'
import json, os, pathlib

path = pathlib.Path(os.environ["SETTINGS_FILE"])
command = os.environ["HOOK_COMMAND"]

settings = {}
if path.exists():
    try:
        loaded = json.loads(path.read_text())
        if isinstance(loaded, dict):
            settings = loaded
        else:
            print(f"warning: {path} is not a JSON object, rewriting it")
    except json.JSONDecodeError:
        print(f"warning: {path} is not valid JSON, rewriting it")

hooks = settings.setdefault("hooks", {})
if not isinstance(hooks, dict):
    hooks = settings["hooks"] = {}
matchers = hooks.setdefault("SessionStart", [])
if not isinstance(matchers, list):
    matchers = hooks["SessionStart"] = []

for matcher in matchers:
    if not isinstance(matcher, dict):
        continue
    for hook in matcher.get("hooks", []):
        if isinstance(hook, dict) and "session-start.sh" in str(hook.get("command", "")):
            print("SessionStart hook already registered, leaving it as is")
            raise SystemExit(0)

matchers.append({"hooks": [{"type": "command", "command": command}]})
path.write_text(json.dumps(settings, indent=2) + "\n")
print(f"registered the hook in {path.name}")
PY
  else
    echo "error: python3 is required to edit .claude/settings.json" >&2
    echo "       add this SessionStart hook by hand: $HOOK_COMMAND" >&2
    exit 1
  fi
}

register_hook

echo
echo "Next: commit .claude/ and merge it into the project's default branch."
